### ISSUE TITLE
I am getting error messages when trying to use it

### ISSUE THREAD

**Issue by Zero3K** [zhangyoujia/hd_write_verify#1]
*subject*

They both happen under Windows 10 and Windows 7. Here's a screenshot of it being ran under Windows 10:

![image](https://github.com/zhangyoujia/hd_write_verify/assets/6194332/6d884fcd-b739-4a45-8b40-fc155d45b76a)

**Comment by Zero3K** [comment]
Here's what happens under Windows 7:

![image](https://github.com/zhangyoujia/hd_write_verify/assets/6194332/889296af-df62-42fa-999a-a30993af02ba)

**Comment by zhangyoujia** [comment]
> _subject_
> 
> They both happen under Windows 10 and Windows 7. Here's a screenshot of it being ran under Windows 10:
> 
> ![image](https://private-user-images.githubusercontent.com/6194332/289580897-6d884fcd-b739-4a45-8b40-fc155d45b76a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI0NDk1NDUsIm5iZiI6MTcwMjQ0OTI0NSwicGF0aCI6Ii82MTk0MzMyLzI4OTU4MDg5Ny02ZDg4NGZjZC1iNzM5LTRhNDUtOGI0MC1mYzE1NWQ0NWI3NmEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIxMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMTNUMDYzNDA1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Y2M0NmY3ZWU0ODk1MWYwMGI1NTU1NjNlNzU4YzA2YWU3N2QwMDcyNThjNzY1NmExNGNhMjNjYjU3NGMwOWRjOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.jQksL_hCcCp0bPa_uX-_K_Qk5u_JEd65-Tgg0bCJytQ)

@Zero3K It is dangerous to test the SYSTEM DISK with LBA tools, Please use the LBA tools to test the DATA DISK and make sure that you have permission to write to the disk.

**Comment by zhangyoujia** [comment]
> > _subject_
> > They both happen under Windows 10 and Windows 7. Here's a screenshot of it being ran under Windows 10:
> > ![image](https://private-user-images.githubusercontent.com/6194332/289580897-6d884fcd-b739-4a45-8b40-fc155d45b76a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI0NDk1NDUsIm5iZiI6MTcwMjQ0OTI0NSwicGF0aCI6Ii82MTk0MzMyLzI4OTU4MDg5Ny02ZDg4NGZjZC1iNzM5LTRhNDUtOGI0MC1mYzE1NWQ0NWI3NmEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIxMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMTNUMDYzNDA1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Y2M0NmY3ZWU0ODk1MWYwMGI1NTU1NjNlNzU4YzA2YWU3N2QwMDcyNThjNzY1NmExNGNhMjNjYjU3NGMwOWRjOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.jQksL_hCcCp0bPa_uX-_K_Qk5u_JEd65-Tgg0bCJytQ)
> 
> @Zero3K It is dangerous to test the SYSTEM DISK with LBA tools, Please use the LBA tools to test the DATA DISK and make sure that you have permission to write to the disk.

@Zero3K \\\\.\phyiscaldrive0 is the FIRST DISK of your computer, and the operating system is installed in it, you do not have permission to write to the SYSTEM DISK.

**Comment by Zero3K** [comment]
Well, it messed up my hard drive. I think the partition table was the only thing that was deleted. Am I right or wrong?

**Comment by zhangyoujia** [comment]
> Well, it messed up my hard drive. I think the partition table was the only thing that was deleted. Am I right or wrong?

![image](https://github.com/zhangyoujia/hd_write_verify/assets/30968954/22ff5d5d-4ccd-4b56-9610-12e336ae179a)

**Comment by Zero3K** [comment]
That doesn't give me an answer to my question and I thought that the permission denied error would've stopped it from being overwritten.

**Comment by zhangyoujia** [comment]
> That doesn't give me an answer to my question and I thought that the permission denied error would've stopped it from being overwritten.

That's a problem with the operating system, which didn't succeed in stopping the LBA tool from running.

**Comment by Zero3K** [comment]
Okay.
